theme: jekyll-theme-minimal
title: Kelly Marchisio
logo: thumbnail.png
description: kmarc@jhu.edu

social-network-links:
  github: kellymarchisio
  twitter: cheeesio
  linkedin: kellymarchisio
  google-scholar: BE9tLKwAAAAJ
