theme: jekyll-theme-minimal
title: Kelly Marchisio
description: PhD Student at JHU CLSP

social-network-links:
  github: kellymarchisio
  twitter: cheeesio
  linkedin: kellymarchisio
  google-scholar: BE9tLKwAAAAJ
