theme: jekyll-theme-minimal
title: Kelly Marchisio
logo: me.png
description: PhD Student at JHU CLSP

social-network-links:
  github: kellymarchisio
  twitter: cheeesio
  linkedin: kellymarchisio
  google-scholar: BE9tLKwAAAAJ


author:
  # name             : "Your Sidebar Name"
  avatar           : "me.jpg"
  googlescholar    : "https://scholar.google.com/citations?user=BE9tLKwAAAAJ"
  github: "kellymarchisio"
  twitter: "cheeesio"
  linkedin: "kellymarchisio"
